export const defaultSections = [
  { title: 'BREAKFAST', items: [] },
  { title: 'APPETIZERS', items: [] },
  { title: 'SALADS', items: [] },
  { title: 'SANDWICHES', items: [] },
  { title: 'BURGERS', items: [] },
  { title: 'MAIN COURSES', items: [] },
  { title: 'PASTA & PIZZA', items: [] },
  { title: 'SIDES', items: [] },
  { title: 'SOL CREPERIE', items: [] },
  { title: 'HOT DRINKS', items: [] },
  { title: 'COLD DRINKS', items: [] },
  { title: 'ICED SMOOTHIES', items: [] },
  { title: 'FRESH FRUIT & JUICES', items: [] },
]
